version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34.10
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        managementApiSecret: "your-secret-type"
        databases:
          default:
            connector: postgres
            host: ""
            port: '5432'
            database: ""
            ssl: Boolean
            user: ""
            password: ""
            migrations: ""