version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34.10
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        managementApiSecret: bang
        databases:
          default:
            connector: postgres
            host: ec2-34-192-210-139.compute-1.amazonaws.com
            port: '5432'
            database: d7hv7khgiqrr6s
            ssl: true
            user: obhziluihsnlvl
            password: 8f7bbb7120f57817b22f3b472c2415f4e4d653aca52020820d46d5563b6c8b14
            migrations: true